version: "3.7"

services:
  vat-docs:
    container_name: vat-docs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/usr/share/nginx/html"
    stdin_open: true
    tty: true
    ports:
      - 1337:80
      - 5000:5000
      - 5001:5001
      - 9005:9005
      - 4000:4000
